### ISSUE TITLE
auro-hyperlink: Theme switcher

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#184]
### Is your feature request related to a problem? Please describe.

Theming

### Describe the solution you'd like

A theme switcher is installed so that developers can verify new changes work with both themes and any future themes.

### Describe alternatives you've considered

None

### Exit criteria

A dev can change themes in the dev environment

**Comment by jason-capsule42** [comment]
This ticket is no longer part of the attached PR. Please unlink them.

**Comment by fajar-apri-alaska** [comment]
This issue is BLOCKED currently since the reference on working of a Theme Switcher component is still under development in [this PR](https://github.com/AlaskaAirlines/auro-button/pull/231).
This issue should be UNBLOCKED when it is either below points:
- PR mentioned above is accepted and merged, or
- There is auro-themeswitcher component that can be used instead of creating a theme-switcher on each auro components

**Comment by braven112** [comment]
closing this issue since we'll come up with a new way to show themes across components.
