### ISSUE TITLE
auro-hyperlink: Still relies on Orion components

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-hyperlink#80]
Because this still relies on Orion components, it will not work on the latest version of Node.

**Comment by blackfalcon** [comment]
Can you provide the error stack? Is this with installing it into an app or getting the demo repo itself up and running? 

For the component itself being installed into an app, there should be no dependency that does not work with node 16. 

Developing on auro-hyperlink will get restricted because of a dev dependency on `wc-sass-render` where the current version still has a dependency on `node-sass` and `node-sass` does not work on 16. 

I have a merged PR on that project https://github.com/tristanMatthias/wc-sass-render/pull/21 but the owner has not yet released a new version of the npm.

**Comment by braven112** [comment]
Auro (public) the latest version of wc-sass-render v1.4 has been released. This update removes the last dependency we had on Node Sass and thus removes any issues we had with Node 16. 
 
Tf you are working on a project and currently cannot use Node 16 (this only applies to projects created with the WC-Generator 3.x), update wc-sass-render to v1.4 and you should be good to go!

**Comment by blackfalcon** [comment]
Testing this with a Node 16 env revealed other dependencies that will not work in Node 16 without more updates. For now, we will have to maintain that this repo for development purposes will be restricted to Node 14. 

The efforts to [upgrade](https://github.com/AlaskaAirlines/auro-hyperlink/issues/39) the repo is in our backlog, but not a critical priority at this time. 

Node 16 support is something that we want to support, but core dependencies that won't work in 16 is causing some pain.
